name: Check code formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cpp-format-check:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
            build-essential \
            clang-format-18

    - name: Test formatting
      run: |
        ./scripts/formatting/check-formatting.sh /usr/bin/clang-format-18
