#ifndef DYAD_COMMON_DYAD_PROFILER_H
#define DYAD_COMMON_DYAD_PROFILER_H
#if defined(DYAD_HAS_CONFIG)
#include <dyad/dyad_config.hpp>
#else
#error "no config"
#endif

#ifdef DYAD_PROFILER_DFTRACER  // DFTRACER
#include <dftracerr/dftracer.h>
#endif

// clang-format off
#ifdef __cplusplus
#ifdef DYAD_PROFILER_NONE
  #define DYAD_CPP_FUNCTION() DYAD_NOOP_MACRO
  #define DYAD_CPP_FUNCTION_UPDATE(key, value) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_START(name) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_END(name) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_UPDATE(name) DYAD_NOOP_MACRO
#elif defined(DYAD_PROFILER_PERFFLOW_ASPECT) // PERFFLOW_ASPECT
  #define DYAD_CPP_FUNCTION() DYAD_NOOP_MACRO
  #define DYAD_CPP_FUNCTION_UPDATE(key, value) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_START(name) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_END(name) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_UPDATE(name) DYAD_NOOP_MACRO
#elif defined(DYAD_PROFILER_CALIPER) // CALIPER
  #define DYAD_CPP_FUNCTION() DYAD_NOOP_MACRO
  #define DYAD_CPP_FUNCTION_UPDATE(key, value) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_START(name) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_END(name) DYAD_NOOP_MACRO
  #define DYAD_CPP_REGION_UPDATE(name) DYAD_NOOP_MACRO
#elif defined(DYAD_PROFILER_DFTRACER) // DFTRACER
  #define DYAD_CPP_FUNCTION() DFTRACER_CPP_FUNCTION()
  #define DYAD_CPP_FUNCTION_UPDATE(key, value) DFTRACER_CPP_FUNCTION_UPDATE((key), (value))
  #define DYAD_CPP_REGION_START(name) DFTRACER_CPP_REGION_START((name))
  #define DYAD_CPP_REGION_END(name) DFTRACER_CPP_REGION_END((name))
  #define DYAD_CPP_REGION_UPDATE(name) DFTRACER_CPP_REGION_DYN_UPDATE((name), (key), (value))
#endif
#endif


#ifdef __cplusplus
extern "C" {
#endif

#ifdef DYAD_PROFILER_NONE
  #define DYAD_C_FUNCTION_START() DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_END() DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_UPDATE_INT(key, value) DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_UPDATE_STR(key, value) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_START(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_END(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_UPDATE_INT(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_UPDATE_STR(name) DYAD_NOOP_MACRO
#elif defined(DYAD_PROFILER_PERFFLOW_ASPECT) // PERFFLOW_ASPECT
  #define DYAD_C_FUNCTION_START() DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_END() DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_UPDATE_INT(key, value) DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_UPDATE_STR(key, value) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_START(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_END(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_UPDATE_INT(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_UPDATE_STR(name) DYAD_NOOP_MACRO
#elif defined(DYAD_PROFILER_CALIPER) // CALIPER
  #define DYAD_C_FUNCTION_START() DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_END() DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_UPDATE_INT(key, value) DYAD_NOOP_MACRO
  #define DYAD_C_FUNCTION_UPDATE_STR(key, value) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_START(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_END(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_UPDATE_INT(name) DYAD_NOOP_MACRO
  #define DYAD_C_REGION_UPDATE_STR(name) DYAD_NOOP_MACRO
#elif defined(DYAD_PROFILER_DFTRACER) // DFTRACER
  #define DYAD_C_FUNCTION_START() DFTRACER_C_FUNCTION_START()
  #define DYAD_C_FUNCTION_END() DFTRACER_C_FUNCTION_END()
  #define DYAD_C_FUNCTION_UPDATE_INT(key, value) DFTRACER_C_FUNCTION_UPDATE_INT((key), (value))
  #define DYAD_C_FUNCTION_UPDATE_STR(key, value) DFTRACER_C_FUNCTION_UPDATE_STR((key), (value))
  #define DYAD_C_REGION_START(name) DFTRACER_C_REGION_START((name))
  #define DYAD_C_REGION_END(name) DFTRACER_C_REGION_END((name))
  #define DYAD_C_REGION_UPDATE_INT(name) DFTRACER_C_REGION_UPDATE_INT((name), (key), (value))
  #define DYAD_C_REGION_UPDATE_STR(name) DFTRACER_C_REGION_UPDATE_STR((name), (key), (value))
#endif

#ifdef __cplusplus
}
#endif
// clang-format on

#endif  // DYAD_COMMON_DYAD_PROFILER_H
